Adds invoice API and routes
Lambda-School-Labs/labspt2-rental pull request #59
Opened 2019-03-16 19:48 UTC by mglittleton

2019-03-17 04:47 UTC, mglittleton commented
Ready to rock and roll

2019-03-18 17:07 UTC, juliejonak requested changes
Hold off on merging until Michael has had a chance to look at router.js to set the route to `invoice` not `invoice-items` and ahead of Kyle's large PR merge

2019-03-20 03:29 UTC, mglittleton commented
This should be good to go now. The routes should be correct.

2019-03-21 14:09 UTC, juliejonak approved these changes

2019-03-21 14:10 UTC, merged